module.exports = [
  "var hero = {",
  "  hp: 200,",
  "  shields: null,",
  "  ultimate: null",
  "}",
  "",
  "function Zenyatta() {",
  "  this.name = 'Zenyatta';",
  "  this.hp = 50;",
  "  this.shields = 150",
  "  this.ultimate = new Ultimate('transcendance', { /*...*/ });",
  "}",
  "",
  "Zenyatta.prototype = hero;",
  "", 
  "var z = new Zenyatta();",
  "",
  "",
].join("\n")