module.exports = [
  "// Classical inheritance -- Superclass",
  "function Presenter() {",
  "  this.name   = \"Unknown\";",
  "  this.cool   = false;",
  "  this.volume = \"normal\";",
  "}",
  "",
  "// Classical inheritance -- Subclass",
  "function Speaker() {",
  "  // Use call to run Presenter fn with 'this' context set",
  "  Presenter.call(this);",
  "  this.custom = \"property\"",
  "}",
  "",
  "Speaker.prototype = new Presenter();",
  "Speaker.prototype.constructor = Speaker;",
  "",
  "var bradley = new Speaker();",
  "",
  "/*",
  "{",
  "  volume: \"loud\",     // --> inherited (copied) locally from Presenter",
  "  cool: \"true\",       // --> inherited (copied) locally from Presenter",
  "  custom: \"property\", // --> defined locally on Speaker",
  "  name: \"Unknown\"     // --> inherited (copied) locally from Presenter",
  "}",
  "*/"
].join("\n")